import { makeStyles } from "@material-ui/core";

export const gettingStartedPageStyles = makeStyles(theme => ({
  root: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    padding: "0px 0px",
    overflowY: "auto",
    overflowX: "hidden",
    color: "#ffffff",
    background: "#000000",
    position: "relative",
  },
  picImage: {
    width: 400,
    height: 670,
    position: "absolute",
    top: 64,
    right: 0,
  },
  backBtn: {
    display: "flex",
    alignItems: "center",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "Grifter",
    textTransform: "uppercase",
    cursor: "pointer",
    marginLeft: 39,
    marginTop: 24,
    "& span": {
      marginLeft: 5,
      marginTop: 2,
    },
  },
  smallPlanetImg: {
    position: "absolute",
    left: 127,
    top: 0,
  },
  largePlanetImg: {
    position: "absolute",
    right: 0,
    top: -25,
  },
  header: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "120px 80px 64px",
    zIndex: 1,
  },
  headerTitle: {
    display: "flex",
    flexDirection: "column",
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
  },
  title: {
    fontSize: 72,
    fontWeight: 800,
    lineHeight: "120%",
    fontFamily: "GRIFTER",
    color: "#ED7B7B",
    textTransform: "uppercase",
  },
  createBtn: {
    background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%)",
    borderRadius: 100,
    fontSize: 18,
    fontWeight: 700,
    lineHeight: "22px",
    fontFamily: "GRIFTER",
    padding: "16px 53px 12px",
    color: "#212121",
    cursor: "pointer",
    textTransform: "uppercase",
  },
  content: {
    position: "relative",
    display: "flex",
    flexDirection: "column",
    color: "#ffffff",
    padding: "0px 60px",
    paddingBottom: 150,
    [theme.breakpoints.down("sm")]: {
      padding: "0px 46px",
    },
    [theme.breakpoints.down("xs")]: {
      padding: "0px 26px",
    },
  },
  description: {
    marginTop: 32,
  },
  downloadUnityBtn: {
    background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%)",
    borderRadius: 48,
    fontSize: 18,
    fontWeight: 700,
    fontFamily: "GRIFTER",
    padding: "9px 16px",
    color: "#212121",
    cursor: "pointer",
    marginTop: 24,
    marginBottom: 28,
    display: "flex",
    alignItems: "center",
    width: 257,
    "& span": {
      marginLeft: 10,
      paddingTop: 4,
    },
  },
  orderBox: {
    width: 36,
    height: 36,
    borderRadius: 100,
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    fontFamily: "Grifter",
    color: "#212121",
    paddingTop: 5,
  },
  typo1: {
    fontSize: 20,
    fontWeight: 700,
    lineHeight: "150%",
    fontFamily: "GRIFTER",
    textTransform: "uppercase",
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
  },
  typo2: {
    fontSize: 16,
    fontWeight: 400,
    lineHeight: "155%",
    fontFamily: "Rany",
  },
  typo3: {
    fontSize: 16,
    fontWeight: 400,
    lineHeight: "150%",
    fontFamily: "Rany",
    textTransform: "uppercase",
  },
}));
