import { makeStyles } from "@material-ui/core";

export const manageContentPageStyles = makeStyles(theme => ({
  root: {
    width: "100%",
    height: "100%",
    padding: "0px 0px",
    overflowY: "auto",
    overflowX: "hidden",
    color: "#ffffff",
    backgroundImage: `url(${require("assets/metaverseImages/background_body.png")})`,
    backgroundRepeat: "inherit",
    backgroundSize: "100% 100%",
    position: "relative",
  },
  backBtn: {
    display: "flex",
    alignItems: "center",
    fontSize: 14,
    fontWeight: 700,
    fontFamily: "Grifter",
    textTransform: "uppercase",
    cursor: "pointer",
    marginLeft: 39,
    marginTop: 36,
    "& span": {
      marginLeft: 5,
      marginTop: 2,
    },
  },
  content: {
    height: "100%",
  },
  mainContent: {
    marginTop: 200,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  otherContent: {
    marginTop: 110,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    maxWidth: 1600,
    marginLeft: "auto",
    marginRight: "auto",
    padding: "0 96px",
    position: "relative",
    [theme.breakpoints.down("sm")]: {
      padding: "0 24px",
    },
    [theme.breakpoints.down("xs")]: {
      padding: "0 16px",
    },
  },
  smallPlanetImg: {
    position: "absolute",
    left: 127,
    top: 0,
  },
  largePlanetImg: {
    position: "absolute",
    right: 0,
    top: -25,
  },
  createBtn: {
    background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%)",
    borderRadius: "100px !important",
    fontSize: "18px !important",
    fontWeight: 700,
    lineHeight: "120%",
    fontFamily: "GRIFTER",
    padding: "17px 53px 12px !important",
    color: "#212121 !important",
    cursor: "pointer",
    textTransform: "uppercase",
    height: "50px !important",
    [theme.breakpoints.down("xs")]: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "100%",
    },
  },
  nextBtn: {
    background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%)",
    borderRadius: "100px !important",
    fontSize: "18px !important",
    fontWeight: 700,
    lineHeight: "120%",
    fontFamily: "GRIFTER",
    padding: "8px 53px 12px !important",
    color: "#212121 !important",
    cursor: "pointer",
    textTransform: "uppercase",
    height: "50px !important",
    marginLeft: "10px",
  },
  howToCreateBtn: {
    background: "transparent",
    border: "2px solid #ffffff80",
    borderRadius: 100,
    fontSize: 18,
    fontWeight: 700,
    lineHeight: "120%",
    fontFamily: "GRIFTER",
    color: "#fff",
    padding: "15px 37px 10px",
    cursor: "pointer",
    textTransform: "uppercase",
  },
  createCollectionBtn: {
    background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%)",
    borderRadius: 12,
    fontSize: 16,
    fontWeight: 700,
    lineHeight: "19.2px",
    fontFamily: "GRIFTER",
    padding: "14px 18px",
    color: "#212121",
    cursor: "pointer",
    textTransform: "uppercase",
    display: "flex",
    alignItems: "center",
    "& svg": {
      marginRight: 12,
    },
  },
  button: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%) !important",
    borderRadius: "82px !important",
    width: "249px !important",
    height: "48px !important",
    textTransform: "uppercase",
    fontSize: "18px !important",
    fontWeight: 700,
    color: "#212121 !important",
    cursor: "pointer",
    "& img": {
      marginRight: 12,
    },
    "& .MuiCircularProgress-root": {
      marginRight: 12,
      width: "25px !important",
      height: "25px !important",
      color: "#212121 !important",
    },
  },
  buttons: {
    display: "flex",
    alignItems: "center",
    [theme.breakpoints.down("xs")]: {
      flexDirection: "column",
      "& div:last-child": {
        marginLeft: 0,
        marginTop: 12,
      },
    },
  },
  typo1: {
    fontSize: 40,
    fontWeight: "bold",
    lineHeight: "120%",
    textAlign: "center",
    fontFamily: "GRIFTER",
    textTransform: "uppercase",
    display: "flex",
    "& svg": {
      marginRight: "8px",
    },
    [theme.breakpoints.down("sm")]: {
      fontSize: 30,
      lineHeight: "30px",
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: 22,
      lineHeight: "22px",
      width: 280,
    },
  },
  typo2: {
    fontSize: 62,
    fontWeight: 700,
    lineHeight: "62px",
    textAlign: "center",
    fontFamily: "GRIFTER",
    textTransform: "uppercase",
    marginBottom: 8,
    [theme.breakpoints.down("sm")]: {
      fontSize: "48px",
      lineHeight: "48px",
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: "34px",
      lineHeight: "34px",
      width: 280,
    },
  },
  typo3: {
    fontSize: 16,
    fontWeight: 400,
    lineHeight: "175%",
    fontFamily: "Rany",
    textAlign: "center",
    [theme.breakpoints.down("xs")]: {
      textAlign: "center",
      width: 280,
    },
  },
  typo4: {
    fontSize: 24,
    fontWeight: "bold",
    lineHeight: "120%",
    textAlign: "center",
    fontFamily: "GRIFTER",
    textTransform: "uppercase",
    [theme.breakpoints.down("sm")]: {
      fontSize: 20,
      lineHeight: "30px",
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: 18,
      lineHeight: "22px",
      width: 280,
    },
  },
  sideBox: {
    width: 136,
    height: 171,
    [theme.breakpoints.down("xs")]: {
      width: 68,
      height: 103,
    },
  },
  centerBox: {
    width: 169,
    height: 212,
    [theme.breakpoints.down("xs")]: {
      width: 102,
      height: 129,

      "& img": {
        width: 70,
        height: 70,
      },
    },
  },
  footer: {
    position: "fixed",
    left: 0,
    bottom: 0,
    width: "100%",
    background: "rgba(0, 0, 0, 0.9)",
    backdropFilter: "blur(24px)",
    padding: "14px 212px",
    display: "flex",
    justifyContent: "space-between",
  },
  assetIcon: {
    width: "38px",
    height: "38px",
    background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%)",
  },
}));
