import { makeStyles } from "@material-ui/core";

export const usePageStyles = makeStyles(theme => ({
  container: {
    padding: "32px 0px",
  },
  title: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "26px",
    lineHeight: "120%",
    letterSpacing: "0.02em",
    color: "#FFFFFF",
  },
  fillBtn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center !important",
    background: "#00B4F7 !important",
    padding: "12px 24px 12px !important",
    border: "2px solid rgba(255, 255, 255, 0.18)  !important",
    boxSizing: "border-box",
    borderRadius: "9px  !important",
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "16px !important",
    lineHeight: "120% !important",
    textAlign: "center",
    textTransform: "capitalize",
    color: "#FFFFFF !important",
    opacity: "0.8 !important",
  },
  strokeBtn: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center !important",
    background: "transparent !important",
    padding: "12px 24px 12px !important",
    border: "2px solid rgba(255, 255, 255, 0.18)  !important",
    boxSizing: "border-box",
    borderRadius: "9px  !important",
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "16px !important",
    lineHeight: "120% !important",
    textAlign: "center",
    textTransform: "capitalize",
    color: "#FFFFFF !important",
    opacity: "0.8 !important",
  },
  roundImageBox: {
    width: 89,
    height: 89,
    borderRadius: 14,
    overflow: "hidden",
    "& img": {
      width: "100%",
      height: "100%",
    },
  },
  grayBgContainer: {
    background: "#222222",
    borderRadius: "12px",
    padding: "8px 16px",
  },
  flexContainer: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  betweenContainer: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flex: "1",
    [theme.breakpoints.down("xs")]: {
      alignItems: "initial",
      justifyContent: "initial",
      flexDirection: "column",
    },
  },
  vScroll: {
    display: "flex",
    flexDirection: "column",
    rowGap: "4px",
    height: "230px",
    overflow: "scroll",
  },
  hScroll: {
    display: "flex",
    flexDirection: "row",
    rowGap: "4px",
  },
  typeTag: {
    borderRadius: 4,
    padding: "9px 8px 7.5px",
    textTransform: "uppercase",
    fontSize: 10,
    fontFamily: "Grifter",
    fontWeight: 700,
    color: "#212121",
    display: "inline-block",
  },
  videoContainer: {
    display: "flex",
    height: 468,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  tokenStatContainer: {
    display: "flex",
    gap: "16px",
    width: "max-content",
  },
  playersContainer: {
    display: "flex",
    gap: 24,
  },
  girdContainer: {
    display: "flex",
    columnGap: "36px",
    flexWrap: "wrap",
  },
  subContainer: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  flexWrap: {
    flexBasis: "100%",
  },
  subContent: {
    maxHeight: 400,
  },
  revenueSummaryContainer: {},
  recentTransactionContainer: {},
  scheduledEventContainer: {},
  recentVotingContainer: {},
  updatesContainer: {
    "& .rec-carousel-wrapper": {
      background:
        "linear-gradient(24.09deg, rgba(0, 0, 0, 0) -14.55%, #000000 34.21%, #08BCFF 71.04%, #08BCFF 82.67%)",
      borderRadius: "8px",
      alignItems: "flex-start",
    },
    "& .rec-slider-container": {
      margin: 0,
    },
    "& .rec-pagination": {
      marginBottom: "15px",
      marginLeft: "110px",
    },
    "& .rec-arrow": {
      width: "38px",
      height: "83px",
      background: "rgba(0, 0, 0, 0.7)",
      borderRadius: "4px",
      minWidth: "auto",
      margin: "5px",
      fontWeight: "normal",
      color: "white",
    },
    "& .rec-dot": {
      width: "28.6px",
      height: "3px",
      background: "rgba(255, 255, 255, 0.5)",
      border: "none",
      boxShadow: "none",
      borderRadius: "0",
    },
    "& .rec-dot_active": {
      background: "#00B4F7",
    },
  },
  membersContainer: {},
  Container: {},
  tokenStatItem: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: "8px",
    gap: "8px",
  },
  tokenStatItemTop: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "120%",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    letterSpacing: "0.02em",
    textTransform: "capitalize",
    color: "rgba(255, 255, 255, 0.5)",
  },
  tokenStatItemBottom: {
    display: "flex",
    alignItems: "center",
    gap: "16px",
  },
  typo1: {
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "19px",
    lineHeight: "120%",
    display: "flex",
    alignItems: "center",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    color: "#FFFFFF",
  },
  typo2: {
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "13px",
    lineHeight: "120%",
    display: "flex",
    alignItems: "center",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    color: "rgba(255, 255, 255, 0.5)",
  },
  typo3: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "18px",
    lineHeight: "120%",
    display: "flex",
    alignItems: "center",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    color: "#FFFFFF",
  },
  typo4: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "16px",
    lineHeight: "120%",
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    color: "#E9FF26",
  },
  typo5: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "13px",
    lineHeight: "120%",
    textAlign: "center",
    letterSpacing: "0.05em",
    textTransform: "uppercase",
    color: "#FFFFFF",
  },
  typo6: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "13px",
    lineHeight: "120%",
    display: "flex",
    alignItems: "center",
    letterSpacing: "0.02em",
    textTransform: "uppercase",
    color: "#FFFFFF",
  },
  typo7: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "45px",
    lineHeight: "120%",
    letterSpacing: "0.02em",
  },
  color1: {
    background:
      "linear-gradient(188.39deg, #04FFF0 22.69%, rgba(0, 240, 255, 0) 63.56%), linear-gradient(0deg, #00B4F7, #00B4F7),linear-gradient(90deg, #FFA723 0.72%, #ABFF40 62.22%, #CCFF00 92.81%), linear-gradient(0deg, #ABFF40, #ABFF40)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
  },
  color2: {
    background:
      "linear-gradient(90deg, #FFA723 0.72%, #ABFF40 62.22%, #CCFF00 92.81%), linear-gradient(0deg, #ABFF40, #ABFF40)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
  },
  color3: {
    background: "linear-gradient(90.25deg, #9123FF -3.07%, #4075FF 92.57%)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
  },
  color4: {
    background:
      "linear-gradient(90deg, #FF2330 0.72%, #FF00D6 92.81%),linear-gradient(0deg, #ABFF40, #ABFF40)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
  },
  typo8: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "17px",
    lineHeight: "120%",
    display: "flex",
    alignItems: "flex-end",
    letterSpacing: "0.02em",
    color: "#FFFFFF",
    opacity: "0.7",
  },
  typo9: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "21px",
    lineHeight: "120%",
    textAlign: "center",
    color: "#00B4F7",
  },
  typo10: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "10px",
    lineHeight: "120%",
    textAlign: "center",
    textTransform: "uppercase",
    color: "#FFFFFF",
  },
  typo11: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "120%",
    color: "#FFFFFF",
    opacity: "0.5",
  },
  typo12: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "13px",
    lineHeight: "19px",
    color: "#FFFFFF",
  },
  typo13: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "120%",
    textAlign: "center",
    color: "#FFFFFF",
  },
  typo14: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "14px",
    lineHeight: "104.5%",
    color: "#FFFFFF",
    opacity: "0.77",
  },
  typo15: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "14px",
    lineHeight: "104.5%",
    color: "#FFFFFF",
    opacity: "0.77",
  },
  typo16: {
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "26px",
    lineHeight: "120%",
    letterSpacing: "0.02em",
    color: "#FFFFFF",
    opacity: "0.5",
  },
  typo17: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "16px",
    lineHeight: "120%",
    textAlign: "center",
    color: "#FFFFFF",
  },
  typo18: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: "13px",
    lineHeight: "120%",
    color: "#FFFFFF",
    opacity: "0.5",
  },
}));
