import { makeStyles } from "@material-ui/core/styles";

export const cardStyles = makeStyles(theme => ({
  root: {
    "background": "#0C0C0C",
    "borderRadius": "12px",
    padding: "40px 43px 44px",
    position: "relative",
  },
  card: {
    "background": "#1B1B1B",
    "borderRadius": "12px",
    padding: "29px 30px 28px",
    height: "255px",
  },
  cardTop: {
    height: "120px",
  },
  close: {
    position: "absolute",
    top: 15,
    right: 16,
    cursor: "pointer",
  },
  rabbitImage: {
    width: "38px",
    height: "38px",
    borderRadius: "5px",
    margin: "3px",
  },
  typo1: {
    "fontFamily": "GRIFTER",
    "fontStyle": "normal",
    "fontWeight": "bold",
    "fontSize": "26px",
    "lineHeight": "120%",
    "letterSpacing": "0.02em",
    "color": "#FFFFFF",
  },
  typo2: {
    "fontFamily": "GRIFTER",
    "fontStyle": "normal",
    "fontWeight": "bold",
    "fontSize": "20px",
    "lineHeight": "120%",
    "letterSpacing": "0.02em",
    "color": "#00B4F7",
  },
  typo3: {
    "fontFamily": "GRIFTER",
    "fontStyle": "normal",
    "fontWeight": "bold",
    "fontSize": "20px",
    "lineHeight": "120%",
    "letterSpacing": "0.02em",
    "color": "#FFFFFF",
    "opacity": "0.5",
  },
  typo4: {
    "fontFamily": "GRIFTER",
    "fontStyle": "normal",
    "fontWeight": "bold",
    "fontSize": "18px",
    "lineHeight": "120%",
    "letterSpacing": "0.02em",
    "color": "#FFFFFF"
  },
  typo5: {
    "fontFamily": "Rany",
    "fontStyle": "normal",
    "fontWeight": "normal",
    "fontSize": "14px",
    "lineHeight": "150%",
    "color": "#FFFFFF"
  },
  typo7: {
    "fontFamily": "Rany",
    "fontStyle": "normal",
    "fontWeight": "bold",
    "fontSize": "100px",
    "lineHeight": "120%",
    "letterSpacing": "0.02em",
    textShadow: "1px 2px 0px #6100FF",
    backgroundImage: "linear-gradient(180deg, #00B4F7 21.67%, #6BFFF6 90%)",
    backgroundSize: "100%",
    "WebkitBackgroundClip": "text",
    "MozBackgroundClip": "text",
    "WebkitTextFillColor": "#1B1B1B",
    "MozTextFillColor": "#1B1B1B",
    WebkitTextStroke: "2px transparent",
  },
  typo8: {
    "fontFamily": "Rany",
    "fontStyle": "normal",
    "fontWeight": "bold",
    "fontSize": "100px",
    "lineHeight": "120%",
    "letterSpacing": "0.02em",
    backgroundImage: "linear-gradient(188.39deg, #04FFF0 22.69%, rgba(0, 240, 255, 0) 63.56%),linear-gradient(0deg, #00B4F7, #00B4F7)",
    backgroundSize: "100%",
    "WebkitBackgroundClip": "text",
    "MozBackgroundClip": "text",
    "WebkitTextFillColor": "transparent",
    "MozTextFillColor": "transparent"
  },
  typo9: {
    "fontFamily": "Rany",
    "fontStyle": "normal",
    "fontWeight": "bold",
    "fontSize": "45px",
    "lineHeight": "120%",
    "letterSpacing": "0.02em",
    backgroundImage: "linear-gradient(90deg, #FFA723 0.72%, #ABFF40 62.22%, #CCFF00 92.81%),linear-gradient(0deg, #ABFF40, #ABFF40)",
    backgroundSize: "100%",
    "WebkitBackgroundClip": "text",
    "MozBackgroundClip": "text",
    "WebkitTextFillColor": "transparent",
    "MozTextFillColor": "transparent"
  },
  typo10: {
    "fontFamily": "Rany",
    "fontStyle": "normal",
    "fontWeight": 500,
    "fontSize": "13px",
    "lineHeight": "120%",
    "display": "flex",
    "alignItems": "center",
    "letterSpacing": "0.02em",
    "textTransform": "uppercase",
    "color": "rgba(255, 255, 255, 0.5)"
  },
  typo11: {
    "fontFamily": "GRIFTER",
    "fontStyle": "normal",
    "fontWeight": "bold",
    "fontSize": "19px",
    "lineHeight": "120%",
    "display": "flex",
    "alignItems": "center",
    "letterSpacing": "0.02em",
    "textTransform": "uppercase",
    "color": "#FFFFFF"
  },
  typo12: {
    "fontFamily": "Rany",
    "fontStyle": "normal",
    "fontWeight": 500,
    "fontSize": "13px",
    "lineHeight": "120%",
    "display": "flex",
    "alignItems": "center",
    "letterSpacing": "0.02em",
    "textTransform": "uppercase",
    "color": "rgba(255, 255, 255, 0.5)"
  }
}));
