import { makeStyles } from "@material-ui/core/styles";

export const assetDetailModalStyles = makeStyles(theme => ({
  root: {
    width: "100vw !important",
    maxWidth: "unset !important",
    padding: "0px !important",
    height: "100vh !important",
    borderRadius: "20px !important",
    color: "#fff !important",
    "& > svg": {
      zIndex: 1,
    },
    [theme.breakpoints.down("xs")]: {
      height: "unset !important",
    },
  },
  container: {
    display: "flex",
    background: "#0B151C !important",
    [theme.breakpoints.down("sm")]: {
      flexDirection: "column",
    },
  },
  viewLabel: {
    background: "#FFD43E",
    borderRadius: 6,
    padding: "4px 10px",
    color: "#1C0A4D",
    fontSize: 12,
    fontWeight: 800,
    lineHeight: "104.5%",
    fontFamily: "Rany",
    textTransform: "uppercase",
    width: 265,
  },
  nftInfoSection: {
    width: 580,
    maxWidth: 580,
    background: "#0B151C",
    padding: "32px 32px 40px",
    display: "flex",
    flexDirection: "column",
    [theme.breakpoints.down("sm")]: {
      width: "100%",
      maxWidth: "100%",
      paddingTop: "56px",
    },
    [theme.breakpoints.down("xs")]: {
      padding: "56px 16px 40px",
    },
  },
  nftPreviewSection: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "column",
    height: "100%",
    padding: "48px 40px",
    background: "#151515",
    position: "relative",
    "& > img": {
      objectFit: "contain",
    },
    [theme.breakpoints.down("xs")]: {
      padding: "0 0",
      margin: "24px 0",
      height: "500px",
    },
    [theme.breakpoints.up("sm")]: {
      margin: "16 32px",
      width: "inherit",
    },
    [theme.breakpoints.up("md")]: {
      margin: 0,
      width: "100%",
    },
  },
  rotateText: {
    "& span": {
      marginLeft: 20,
    },
  },
  speaker: {
    marginTop: 40,
    background: "rgba(255, 255, 255, 0.1)",
    border: "0.726449px solid rgba(255, 255, 255, 0.2)",
    borderRadius: 21,
    padding: 8,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  createNftBtn: {
    background: "linear-gradient(90.07deg, #49E9FF 1.26%, #FFFFFF 98.76%), #FFFFFF",
    borderRadius: 48,
    fontSize: 16,
    fontWeight: 600,
    lineHeight: "20px",
    color: "#1C0A4C",
    cursor: "pointer",
    padding: "15px 30px",
    width: 234,
  },
  topOptWrap: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  optSection: {
    display: "flex",
    alignItems: "center",
  },
  creatorinfoSection: {
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
  },
  typo1: {
    fontSize: 14,
    fontWeight: "bold",
    fontFamily: "GRIFTER",
    lineHeight: "104.5%",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  typo11: {
    fontSize: 14,
    fontWeight: "normal",
    fontFamily: "Rany",
    lineHeight: "104.5%",
    "&:hover": {
      textDecoration: "underline",
    },
  },
  typo2: {
    fontSize: 27,
    fontWeight: "bold",
    fontFamily: "GRIFTER",
    color: "white",
    lineHeight: "30px",
  },
  typo3: {
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: "GRIFTER",
    lineHeight: "21px",
    overflowWrap: "break-word",
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  typo4: {
    fontFamily: "Rany",
    fontSize: 14,
    fontWeight: "bold",
    lineHeight: "150%",
    opacity: 0.5,
  },
  typo5: {
    fontSize: 16,
    fontWeight: "normal",
    fontFamily: "Rany",
    lineHeight: "24px",
    color: "white",
    maxWidth: 260,
    textOverflow: "ellipsis",
    overflow: "hidden",
  },
  button: {
    background: "linear-gradient(97.4deg, #8F66FF 14.43%, #4218B5 79.45%) !important",
    borderRadius: "8px !important",
    width: "100% !important",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 600,
    fontSize: "16px",
    lineHeight: "104.5%",
    height: "59px !important",
    marginTop: 48,
    "& svg": {
      marginRight: 16,
    },
  },
}));
