import { makeStyles } from "@material-ui/core/styles";

export const PayRemainingAmountModalStyles = makeStyles(theme => ({
  container: {
    maxWidth: "508px !important",
    padding: "25px !important",
  },
  nameField: {
    margin: "8px 0px 0px 0px",
    fontFamily: "Rany",
    fontWeight: 400,
    fontSize: "14px",
    color: "#ffffff",
  },
  availableCollateral: {
    padding: "23px 31px 23px 31px",
    background: "rgba(218, 230, 229, 0.06)",
    border: "1px solid rgba(255, 255, 255, 0.5)",
    marginTop: "24px",
  },
  collateralText: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "150%",
    letterSpacing: "0.02em",
    color: "#ffffff",
  },
  collateralAmount: {
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "24px",
    lineHeight: "150%",
    letterSpacing: "0.02em",
    background: "linear-gradient(#EDFF1C, #ED7B7B)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
  },
  inputJOT: {
    background: "rgba(144, 155, 255, 0.16)",
    // border: "1px solid #431AB7 !important",
    width: "100%",
    borderRadius: theme.spacing(1),
    padding: theme.spacing(1),
  },
  inputTag: {
    background: "rgba(67, 26, 183, 0.2)",
    width: "100%",
    borderRadius: theme.spacing(1),
    padding: "16px",
    fontFamily: "Grifter",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: "14px",
    lineHeight: "120%",
    color: "#431AB7",
    mixBlendMode: "normal",
    border: "none",
  },
  purpleText: {
    fontFamily: "Grifter !important",
    cursor: "pointer",
    color: "#431AB7",
    fontSize: "16px",
    minWidth: "55px",
    fontWeight: 700,
  },
  usdWrap: {
    display: "flex",
    alignItems: "center",
    [theme.breakpoints.down("sm")]: {
      paddingTop: "0",
    },
  },
  primaryButton: {
    color: "#212121 !important",
    padding: "0 37px !important",
    height: "40px !important",
    background: "linear-gradient(#B7FF5C, #EEFF21) !important",
    borderRadius: "40px",
    border: "none",
    "&:disabled": {
      background: "linear-gradient(#B7FF5C, #EEFF21) !important",
      color: "#212121 !important",
    },
  },
}));
