import { makeStyles } from "@material-ui/core";

export const listStyles = makeStyles(theme => ({
  root: {
    border: "2px solid",
    borderImageSource: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    borderImageSlice: 1,
    width: "100%",
  },
  title: {
    margin: 0,
    marginBottom: 20,
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    fontFamily: "GRIFTER",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 34,
    lineHeight: "40px",
    textTransform: "uppercase",
    width: "100%",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    [theme.breakpoints.down("sm")]: {
      fontSize: 20,
      lineHeight: "24px",
    },
  },
  titleWrapper: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
  },
  textBox: {
    display: "flex",
    flexDirection: "column",
  },
  textTitle: {
    color: "#FFFFFF",
    fontFamily: "Rany",
    fontSize: 14,
    fontWeight: 500,
    lineHeight: "18px",
    margin: 0,
  },
  description: {
    color: "#E9FF26",
    fontFamily: "Rany",
    fontSize: 14,
    lineHeight: "20px",
    margin: 0,
  },
  titleImg: {
    width: 45,
    height: 45,
    borderRadius: 6,
    objectFit: "cover",
    margin: "0 20px",
  },
  accTitle: {
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    fontFamily: "Rany",
    fontSize: 14,
    lineHeight: "20px",
    margin: 0,
  },
  whiteText: {
    color: "#FFFFFF",
    fontFamily: "Rany",
    fontSize: 16,
    fontWeight: 700,
    lineHeight: "22px",
    margin: 0,
  },
  button: {
    backgroundColor: "transparent !important",
    border: "2px solid rgba(255,255,255,0.5) !important",
  },
}));
