import { makeStyles } from "@material-ui/core";

export const modalStyles = makeStyles(theme => ({
  container: {
    backgroundColor: "#0B151C !important",
    boxShadow: "0px 38px 96px 17px rgba(1, 1, 13, 0.25) !important",
    borderRadius: "0 !important",
    width: "682px !important",
    maxWidth: "none !important",
    color: "#2D3047 !important",
    padding: "64px 40px !important",
    "& button": {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      background: "linear-gradient(92.31deg, #EEFF21 -2.9%, #B7FF5C 113.47%)",
      color: "#212121",
      fontFamily: "GRIFTER",
      fontSize: 18,
      fontWeight: 800,
      lineHeight: "120%",
      borderRadius: 34,
      minWidth: 256,
      height: 49,
      paddingLeft: 32,
      paddingRight: 32,
      textTransform: "uppercase",
    },
  },
  gradientContainer: {
    background: "linear-gradient(97.63deg, #A0D800 26.36%, #0DCC9E 80%)",
    color: "white !important",
    "& button": {
      background: "white",
      color: "#2D3047",
    },
  },
  green: {
    color: "#65CB63",
  },
  title: {
    fontSize: 30,
    lineHeight: "40px",
    fontWeight: 800,
    textTransform: "uppercase",
    textAlign: "center",
  },
  subTitle: {
    fontFamily: "GRIFTER",
    fontSize: 24,
    lineHeight: "28px",
    fontWeight: "bold",
    textAlign: "center",
    textTransform: "uppercase",
    color: "#E9FF26",
  },
  description: {
    textAlign: "center",
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "16px",
    lineHeight: "160%",
    color: "white",
    width: "80%",
  },
  cryIcon: {
    width: 96,
    height: 96,
    background: "linear-gradient(97.63deg, #A0D800 26.36%, #0DCC9E 80%)",
    borderRadius: "100%",
    fontSize: 64,
    fontWeight: 800,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  warning: {
    fontSize: 65,
  },
  buttonImage: {
    width: 20,
    height: 20,
  },
  logoImage: {
    width: 64,
    height: 64,
  },
  progress: {
    border: "1px solid rgba(64, 70, 88, 0.19)",
    padding: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "100%",
  },
}));
