import { makeStyles } from "@material-ui/core/styles";

export const RentNFTModalStyles = makeStyles(theme => ({
  container: {
    padding: "0px !important",
  },
  title: {
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
    fontSize: "24px",
    width: "fit-content",
    fontWeight: 700,
    fontFamily: "Grifter",
    textTransform: "uppercase",
    marginTop: 24,
  },
  purpleText: {
    background: "linear-gradient(#EDFF1C, #ED7B7B)",
    "-webkit-text-fill-color": "transparent",
    "-webkit-background-clip": "text",
    fontSize: "18px",
    fontWeight: 400,
    fontFamily: "Grifter",
    width: "fit-content",
  },
  subTitle: {
    color: "#ffffff",
    fontFamily: "Rany",
    fontWeight: "normal",
    fontSize: "14px",
    lineHeight: "20px",
  },
  primaryButton: {
    color: "#212121 !important",
    padding: "0 37px !important",
    height: "40px !important",
    background: "linear-gradient(#B7FF5C, #EEFF21) !important",
    borderRadius: "40px",
    border: "none",
    "&:disabled": {
      background: "linear-gradient(#B7FF5C, #EEFF21) !important",
      color: "#212121 !important",
    },
  },
  maxTime: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "14px",
    color: "#F2604C",
    cursor: "pointer",
  },
  nameField: {
    fontFamily: "Rany",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "14px",
    color: "#ffffff",
  },
  inputDays: {
    backgroundColor: "#172227 !important",
    border: "1px solid rgba(218, 218, 219, 0.59) !important",
    width: "100%",
    padding: theme.spacing(1),
    color: "#ffffff60 !important",
    borderRadius: "unset !important",
    fontFamily: "Rany",
  },
  inputLabel: {
    fontFamily: "Rany",
    color: "#ffffff",
    fontSize: "14px",
    lineHeight: "120%",
    fontWeight: "bold",
  },
  borderBox: {
    background: "linear-gradient(301.58deg, #ED7B7B 32.37%, #EDFF1C 100.47%)",
    padding: 2,
    marginTop: 8,
  },
  box: {
    padding: "23px 18px",
    background: "rgb(11, 21, 28)",
    display: "flex",
    justifyContent: "space-between",
  },
  amountLabel: {
    color: "#ffffff",
    fontSize: "16px",
    fontFamily: "Rany",
    lineHeight: "150%",
    whiteSpace: "nowrap",
  },
}));
